title: Channa
suffix: Channa Livewell
description: "Healing food, food as medicine, culinary medicine, lifestyle medicine, teaching kitchen, wellness space
อาหารเพื่อสุขภาพ อาหารคลีน อาหารผู้สูงอายุ อาหารโรคเรื้องรัง อาหารโรคเบาหวาน อาหารโรคความดัน อาหารโรคไขมัน อาหารโรคมะเร็ง อาหารโรคไต อาหารวีแกน อาหารมังสวิรัติ อาหาร plant-based เรียนทำอาหารสุขภาพ เรียนทำอาหารคลีน คอร์สสอนทำอาหารสุขภาพ สอนทำอาหารสุขภาพ สอนทำอาหารคลีน เรียนทำอาหารสุขภาพ เรียนทำอาหารคลีน"

name: Channa Livewell - name
url: "https://www.channalivewell.com"
baseurl: ""
base_canonical: "https://www.channalivewell.com"
permalink: 

social:
   facebook: https://www.facebook.com/channalivewell
   instagram: https://www.instagram.com/channa.livewell/
   line: https://lin.ee/u6dxl3k
   maps: https://maps.app.goo.gl/r4ytL8TJQWuVhJz37
   email: "mailto:channa.livewell@gmail.com"
   github: https://github.com/channalivewell/channalivewell.github.io

delivery:
   robinhood: https://bit.ly/channarobinhood
   lineman: https://wongn.ai/183t4
   grab: https://bit.ly/channagrab

google_analytics: "G-8J35TTB3MP"

form:
   class: "https://forms.gle/XRYRPH4Zrrx6zBYV8"
   delivery: 
   feedback: "https://forms.gle/TFFC5dbuTBNyBs2fA"
