title: Channa
suffix: Channa Livewell
description: Channa Livewell -- description

name: Channa Livewell - name
url: "https://channalivewell.com"
baseurl: ""
base_canonical: "https://channalivewell.com"
permalink: 

social:
   facebook: https://www.facebook.com/channalivewell
   instagram: https://www.instagram.com/channa.livewell/
   line: https://lin.ee/u6dxl3k
   maps: https://goo.gl/maps/gzdNNmrSArnxisTG6
   email: channa.livewell@gmail.com
   github: https://github.com/channalivewell/channalivewell.github.io

google_analytics: "G-8J35TTB3MP"

form:
   payment: "https://forms.gle/gRcuzqJp1eoqoSFT7"
   bentoOrder_01:
   bentoOrder_02:
   bentoOrder_03:
   dishoOrder_01:
   dishoOrder_02:
   dishoOrder_03: