title: Channa
suffix: Channa Livewell
description: "Healing food, food as medicine, culinary medicine, lifestyle medicine, teaching kitchen, wellness space
อาหารเพื่อสุขภาพ อาหารคลีน อาหารผู้สูงอายุ อาหารโรคเรื้องรัง อาหารโรคเบาหวาน อาหารโรคความดัน อาหารโรคไขมัน อาหารโรคมะเร็ง อาหารโรคไต อาหารวีแกน อาหารมังสวิรัติ อาหาร plant-based เรียนทำอาหารสุขภาพ เรียนทำอาหารคลีน คอร์สสอนทำอาหารสุขภาพ สอนทำอาหารสุขภาพ สอนทำอาหารคลีน เรียนทำอาหารสุขภาพ เรียนทำอาหารคลีน"

name: Channa Livewell - name
url: "https://www.channalivewell.com"
baseurl: ""
base_canonical: "https://www.channalivewell.com"
permalink: 

social:
   facebook: https://www.facebook.com/channalivewell
   instagram: https://www.instagram.com/channa.livewell/
   line: https://lin.ee/u6dxl3k
   maps: https://maps.app.goo.gl/r4ytL8TJQWuVhJz37
   embeded_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3872.508447596876!2d100.56696771483244!3d13.928304090233336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30e2837523216503%3A0x4f5a44e1c21d52e3!2zQ2hhbm5hIOC4iuC4suC4jeC4meC4sg!5e0!3m2!1sen!2sth!4v1651297470372!5m2!1sen!2sth
   email: "mailto:channa.livewell@gmail.com"
   github: https://github.com/channalivewell/channalivewell.github.io

delivery:
   robinhood: https://bit.ly/channarobinhood
   lineman: https://wongn.ai/183t4
   grab: https://bit.ly/channagrab

google_analytics: "G-8J35TTB3MP"

form:
   class: "https://forms.gle/XRYRPH4Zrrx6zBYV8"
   delivery: 
   feedback: "https://forms.gle/TFFC5dbuTBNyBs2fA"
