title: Channa
suffix: Channa Livewell
description: healing food, food as medicine, culinary medicine, lifestyle medicine

name: Channa Livewell - name
url: "https://www.channalivewell.com"
baseurl: ""
base_canonical: "https://www.channalivewell.com"
permalink: 

social:
   facebook: https://www.facebook.com/channalivewell
   instagram: https://www.instagram.com/channa.livewell/
   line: https://lin.ee/u6dxl3k
   maps: https://goo.gl/maps/gzdNNmrSArnxisTG6
   email: "mailto:channa.livewell@gmail.com"
   github: https://github.com/channalivewell/channalivewell.github.io

google_analytics: "G-8J35TTB3MP"

form:
   class: "https://forms.gle/XRYRPH4Zrrx6zBYV8"
   delivery: 
   feedback: "https://forms.gle/TFFC5dbuTBNyBs2fA"
